import { useState } from "react";

const G = {
  bg: "#0a1628",
  card: "rgba(255,255,255,0.04)",
  border: "rgba(255,255,255,0.1)",
  accent: "#f59e0b",
  accentLight: "#fcd34d",
  blue: "#3b82f6",
  teal: "#14b8a6",
  text: "#f1f5f9",
  muted: "#94a3b8",
  green: "#22c55e",
};

const styles = {
  app: {
    minHeight: "100vh",
    background: `radial-gradient(ellipse at 20% 10%, #1e3a5f 0%, ${G.bg} 60%)`,
    fontFamily: "'Palatino Linotype', 'Book Antiqua', Palatino, serif",
    color: G.text,
  },
  header: {
    borderBottom: `1px solid ${G.border}`,
    padding: "0 24px",
    background: "rgba(0,0,0,0.3)",
    backdropFilter: "blur(12px)",
    position: "sticky",
    top: 0,
    zIndex: 100,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: "64px",
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  logoIcon: {
    width: "36px",
    height: "36px",
    background: `linear-gradient(135deg, ${G.accent}, ${G.teal})`,
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "18px",
  },
  logoText: {
    fontSize: "18px",
    fontWeight: "800",
    color: G.text,
    letterSpacing: "-0.02em",
  },
  logoSub: {
    fontSize: "11px",
    color: G.muted,
    letterSpacing: "0.15em",
    textTransform: "uppercase",
  },
  badge: {
    background: `rgba(245,158,11,0.15)`,
    border: `1px solid rgba(245,158,11,0.3)`,
    color: G.accent,
    fontSize: "11px",
    padding: "3px 10px",
    borderRadius: "20px",
    fontFamily: "monospace",
  },
  main: { maxWidth: "860px", margin: "0 auto", padding: "32px 20px 60px" },
  sectionTitle: {
    fontSize: "11px",
    fontWeight: "700",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: G.accent,
    marginBottom: "14px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  card: {
    background: G.card,
    border: `1px solid ${G.border}`,
    borderRadius: "14px",
    padding: "24px",
    marginBottom: "20px",
  },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" },
  grid3: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "16px" },
  label: {
    display: "block",
    fontSize: "11px",
    fontWeight: "700",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    color: G.teal,
    marginBottom: "6px",
